# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
# - stateMachineAPI
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'caminomediagroup/state-machine-api:$(build.buildId)'

steps:

- script: docker build -f Dockerfile -t $(imageName) .
- script: docker login -u caminomediagroup -p Ci08719544
- script: docker push $(imageName)
  displayName: 'docker build'
